### ISSUE TITLE
Qor Logo Discussion

### ISSUE THREAD

**Issue by mamarilmanson** [flipcoder/qor#5]
not the exact thing in mind... but this is a draft by the way... :)
![qorlogodraft](https://cloud.githubusercontent.com/assets/3820189/13037670/37bd9da0-d3c1-11e5-86f6-f51283a3d54b.png)

**Comment by flipcoder** [comment]
It's a good start.  I like gray and black for colors.  Could make it look good on top of black or white background.  I think the "\" on the Q should be shorter though.  :)   Otherwise it looks like a magnifying glass.

**Comment by mamarilmanson** [comment]
Ok... got it... :+1:

**Comment by mamarilmanson** [comment]
![qorlogodraft3](https://cloud.githubusercontent.com/assets/3820189/13208267/11af8560-d952-11e5-9e8d-f0053f771007.png)

![qorlogodraft2](https://cloud.githubusercontent.com/assets/3820189/13208235/a3714516-d951-11e5-851f-b3948fdcc968.png)

Qor logo draft 2 and 3... I changed it so it tries to reach the "edgy" look and feel of Unity, Unreal and Cryengine logos...

**Comment by flipcoder** [comment]
nice, looking good so far

**Comment by mamarilmanson** [comment]
any input you might have as to what direction we might take? :)

**Comment by flipcoder** [comment]
looks similar to quake logo but sideways, might need to differentiate it more.  It also looks kinda like a bird face. Haha.  Let me think a little bit, I may have some ideas shortly.  Hmm  I like it though!

**Comment by mamarilmanson** [comment]
When you mentioned the quake logo that's just the time I searched about it... just a disclaimer... I did not take any references from the internet but just a self developing concept as I was sketching things... 

but what idea it is to me is a sort of a spartan helmet... :)

**Comment by flipcoder** [comment]
Oh yeah I see that now that you mention it

**Comment by mamarilmanson** [comment]
:D

Need to brainstorm more... :)

**Comment by flipcoder** [comment]
oh looked at quake logo its not as similar as I thought

**Comment by mamarilmanson** [comment]
:D

**Comment by flipcoder** [comment]
The only thing I could see improved would be the dot in the middle might look good some other way.  (Not a gfx guy so i have no idea how much that is worth to you :P)

Also I have to agree with the edginess factor.  It definitely fits for an engine

**Comment by mamarilmanson** [comment]
As a gfx guy... I can tell you that in some cases I look to https://logopond.com/ for inspirations and references that best express what is needed to express when making a design(in this case a logo)...

I would suggest you browse around and build a strong sense of what we might be able to build upon what I have delivered to you today... :D

**Comment by flipcoder** [comment]
![Qor](https://raw.githubusercontent.com/flipcoder/qor/master/qor.png)

Finally got around to doing one.
